version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: tabanok-db
    environment:
      POSTGRES_DB: tabanok
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: blackcode13/tabanok:backend-latest
    container_name: tabanok-backend
    environment:
      DATABASE_URL: postgres://postgres:root@postgres:5432/tabanok
    depends_on:
      - postgres
    ports:
      - "3001:3000"
    restart: always

  frontend:
    image: blackcode13/tabanok:frontend-latest
    container_name: tabanok-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: always

volumes:
  postgres_data:
