services:
  postgres:
    image: postgres:latest
    container_name: database
    env_file:
      - .env
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/files/sql/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./backend/files/sql/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    restart: always

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - '8000:8000'
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - '3000:80'
    restart: always

volumes:
  postgres_data:
