name: Deploy Backend to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build backend Docker image
        run: docker build -t blackcode13/tabanok:backend-latest -f backend/Dockerfile .

      - name: Build frontend Docker image
        run: docker build -t blackcode13/tabanok:frontend-latest -f frontend/Dockerfile ./frontend

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push backend image to Docker Hub
        run: docker push blackcode13/tabanok:backend-latest

      - name: Push frontend image to Docker Hub
        run: docker push blackcode13/tabanok:frontend-latest

      # Despliegue automático por SSH al servidor y reinicio de contenedores
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull blackcode13/tabanok:backend-latest
            docker pull blackcode13/tabanok:frontend-latest
            docker stop tabanok-backend || true
            docker rm tabanok-backend || true
            docker stop tabanok-frontend || true
            docker rm tabanok-frontend || true
            docker run -d --name tabanok-backend -p 3001:3000 blackcode13/tabanok:backend-latest
            docker run -d --name tabanok-frontend -p 3000:80 blackcode13/tabanok:frontend-latest
